apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PFE-WEVIOO/joget-helm.git
    targetRevision: main
    path: deployment-configuration
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: joget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

