apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PFE-WEVIOO/joget-argocd.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: joget
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
