replicaCount: 3

image:
  repository: motrabelsi10/joget-v7
  tag: latest
  pullPolicy: Always

mysql:
  host: mysql.joget.svc.cluster.local
  database: jwdb
  username: tomcat
  password: tomcat

service:
  type: NodePort
  portHttp: 8080
  portHttps: 9080
  nodePortHttp: 32325

nodeSelector:
  kubernetes.io/hostname: k8s-worker1
